# Generated by Django 3.1 on 2020-09-13 15:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makaleler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='baslik',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='icerik',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
    ]
