# Generated by Django 3.1 on 2020-09-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makaleler', '0002_auto_20200913_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ek : '),
        ),
        migrations.CreateModel(
            name='MakaleYorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_yazar', models.CharField(max_length=50, verbose_name='Adınız : ')),
                ('yorum_icerik', models.CharField(max_length=200, verbose_name='Yorumunuz : ')),
                ('yorum_tarihi', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='makaleler.makale', verbose_name='Yorum Yapın')),
            ],
        ),
    ]
