# Generated by Django 3.1 on 2020-09-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makaleler', '0003_auto_20200914_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-olusturulma_tarihi']},
        ),
        migrations.AlterModelOptions(
            name='makaleyorum',
            options={'ordering': ['-yorum_tarihi']},
        ),
    ]
